import type { Question } from '../types'

export const questions: Question[] = [
  // ---------- Revit ----------
  {
    id: 1,
    category: 'Revit',
    prompt:
      'Which family category is built directly within the project environment and cannot be loaded from an external file (unlike doors or windows)?',
    options: ['System families', 'Loadable families', 'In-place families', 'Global parameter families'],
    correctIndex: 0,
    explanation:
      'System families — walls, floors, roofs, ceilings — are defined inside the project/template itself. Loadable families (doors, windows, furniture) live in external .rfa files and get loaded in; in-place families are one-off geometry modeled for a single project.',
  },
  {
    id: 2,
    category: 'Revit',
    prompt: 'Which Revit feature divides a central model into ownable portions so multiple users can edit it simultaneously?',
    options: ['Design Options', 'Worksets', 'Groups', 'Phases'],
    correctIndex: 1,
    explanation:
      'Worksharing splits a model into worksets that individual users can "check out," enabling parallel editing against a central file without overwriting each other\'s work.',
  },
  {
    id: 3,
    category: 'Revit',
    prompt: 'A View Template in Revit is primarily used to:',
    options: [
      'Apply a consistent set of visibility, graphics, and detail settings across many views at once',
      'Store shared parameters for scheduling',
      'Define a building\'s coordinate system',
      'Convert a family into a system family',
    ],
    correctIndex: 0,
    explanation:
      'A view template bundles view properties (V/G overrides, detail level, scale, discipline) so you can apply the same look to dozens of views instantly, instead of configuring each one by hand.',
  },
  {
    id: 4,
    category: 'Revit',
    prompt: 'Shared parameters in Revit are mainly used to:',
    options: [
      'Make a custom parameter available across multiple families and projects so it can be tagged and scheduled consistently',
      'Control only the geometry of a single family',
      'Replace the need for system families',
      'Store rendering material overrides',
    ],
    correctIndex: 0,
    explanation:
      'Shared parameters live in an external .txt definition file, giving them a stable GUID that lets the same parameter be reused, tagged, and scheduled consistently across many families and projects.',
  },
  {
    id: 5,
    category: 'Revit',
    prompt: 'Which Revit datum element defines horizontal floor-to-floor elevations, as distinct from Grids?',
    options: ['Grids', 'Levels', 'Reference planes', 'Scope boxes'],
    correctIndex: 1,
    explanation:
      'Levels are horizontal datum planes that set story elevations (e.g., floor-to-floor heights). Grids, by contrast, are vertical reference lines typically used to locate columns and structure in plan.',
  },
  {
    id: 6,
    category: 'Revit',
    prompt: 'Which file extension is a native Revit project file?',
    options: ['.rvt', '.rfa', '.nwc', '.rte'],
    correctIndex: 0,
    explanation:
      '.rvt is the project file. .rfa is a loadable family file, .rte is a project template, and .nwc is a Navisworks cache format, not a Revit format at all.',
  },
  {
    id: 7,
    category: 'Revit',
    prompt: 'Phasing in Revit is primarily used to:',
    options: [
      'Model existing conditions, demolition, and new construction as distinct stages within one project',
      'Manage worksets between disciplines',
      'Control rendering quality settings',
      'Split one model permanently into several linked files',
    ],
    correctIndex: 0,
    explanation:
      'Phases assign elements to construction stages (Existing, Demolition, New Construction) and, combined with phase filters, control how each stage is displayed — essential on renovation and phased-build projects.',
  },
  {
    id: 8,
    category: 'Revit',
    prompt: 'Compared to importing geometry, what does linking another Revit model (RVT link) give you?',
    options: [
      'A live, updatable reference that can be reloaded when the source file changes',
      'A permanently merged, static copy of the geometry',
      'Automatic conversion of the linked file into system families',
      'A rendering-only preview with no coordination value',
    ],
    correctIndex: 0,
    explanation:
      'A linked RVT stays as an external reference — reload it and you pick up the source file\'s latest changes. An import instead pastes in a static, disconnected copy of the geometry.',
  },

  // ---------- Navisworks ----------
  {
    id: 9,
    category: 'Navisworks',
    prompt: 'Which Navisworks format is a lightweight geometry cache generated by exporting from an authoring tool like Revit?',
    options: ['.nwc', '.nwd', '.nwf', '.rvt'],
    correctIndex: 0,
    explanation:
      '.nwc (Navisworks Cache) holds converted, lightweight geometry from the source app. .nwd is a published document with everything embedded, and .nwf is a session file that only stores links, not geometry.',
  },
  {
    id: 10,
    category: 'Navisworks',
    prompt: 'Which Navisworks file format saves links to source files, viewpoints, and clash results, WITHOUT embedding the model geometry itself?',
    options: ['.nwf', '.nwd', '.nwc', '.nwt'],
    correctIndex: 0,
    explanation:
      'An NWF (Navisworks file set) keeps references to the original source files rather than embedding geometry — small file size, but the linked sources must stay reachable at their original paths.',
  },
  {
    id: 11,
    category: 'Navisworks',
    prompt: 'In Clash Detective, what is a "hard clash"?',
    options: [
      'Two objects physically intersect/overlap in 3D space',
      'Two objects are within a defined clearance distance but not touching',
      'A duplicate object exists in the model',
      'An object is missing required metadata',
    ],
    correctIndex: 0,
    explanation:
      'A hard clash is a genuine geometric intersection. A "clearance" (soft) clash instead flags objects that come within a set tolerance without truly overlapping — useful for checking maintenance access, for example.',
  },
  {
    id: 12,
    category: 'Navisworks',
    prompt: 'What does the TimeLiner tool in Navisworks do?',
    options: [
      'Links model objects to a construction schedule to simulate 4D sequencing',
      'Detects geometric clashes between disciplines',
      'Extracts quantities for cost estimation',
      'Manages worksets across linked models',
    ],
    correctIndex: 0,
    explanation:
      'TimeLiner attaches model elements (or selection sets) to schedule tasks — imported from Microsoft Project or Primavera, or entered manually — to produce a 4D construction sequence animation.',
  },
  {
    id: 13,
    category: 'Navisworks',
    prompt: 'Which Navisworks tool extracts counts, areas, and volumes from the federated model for takeoff purposes?',
    options: ['Quantification', 'Clash Detective', 'Animator', 'Presenter'],
    correctIndex: 0,
    explanation:
      'The Quantification workbook pulls and organizes takeoff quantities straight from model geometry and properties, supporting 5D (cost-linked) BIM workflows.',
  },
  {
    id: 14,
    category: 'Navisworks',
    prompt: 'In Clash Detective, a test comparing "Selection Set A vs Selection Set B" is typically used to:',
    options: [
      'Check two distinct discipline groups (e.g., structure vs. ductwork) against each other',
      'Find internal duplicate geometry within a single model only',
      'Compare two separate Navisworks software versions',
      'Validate file format compatibility',
    ],
    correctIndex: 0,
    explanation:
      'A vs. B tests two distinct selection sets against each other — the standard discipline-to-discipline coordination check. A "vs. Self" test instead looks for clashes within one set alone.',
  },
  {
    id: 15,
    category: 'Navisworks',
    prompt: 'What does "Switchback" let a coordinator do when working with a linked Revit model in Navisworks?',
    options: [
      'Select an object in Navisworks and jump directly to the same element in its native authoring application',
      'Reverse a saved clash test result',
      'Undo the last saved viewpoint',
      'Convert an NWD file back into an NWC',
    ],
    correctIndex: 0,
    explanation:
      'Switchback selects an element in Navisworks and opens that same element highlighted inside its native authoring tool (Revit, AutoCAD, etc.), provided the matching plugin/version is installed — speeding up issue resolution.',
  },

  // ---------- BIM Coordination ----------
  {
    id: 16,
    category: 'Coordination',
    prompt: 'What is a "federated model" in BIM coordination?',
    options: [
      'A combined view formed by aggregating multiple discipline models, each remaining a separate, independently managed source file',
      'A single authoritative model edited by all disciplines in real time',
      'A model exported purely for rendering',
      'The archived, final version of a design',
    ],
    correctIndex: 0,
    explanation:
      'Federation links/aggregates discipline models (architecture, structure, MEP) together for coordination and clash checking, while each discipline keeps authoring and owning its own native file.',
  },
  {
    id: 17,
    category: 'Coordination',
    prompt: 'In BIM, what does "LOD" (Level of Development) describe?',
    options: [
      'How much geometric detail and reliable information an element carries at a given project stage',
      'Purely aesthetic/visual detail for renderings',
      'The structural grid alignment of a building',
      'A project\'s document/deliverable register',
    ],
    correctIndex: 0,
    explanation:
      'LOD (often paired with LOI, Level of Information) describes how much geometric detail and non-graphical data can be relied upon for an element at a given stage, per frameworks like the BIMForum LOD specification.',
  },
  {
    id: 18,
    category: 'Coordination',
    prompt: 'Which open, vendor-neutral file format is designed to exchange BIM data between different software platforms?',
    options: ['IFC (Industry Foundation Classes)', 'DWG', 'RVT', 'SKP'],
    correctIndex: 0,
    explanation:
      'IFC, maintained by buildingSMART, is the open schema built specifically for interoperable exchange of building model data across authoring tools from different vendors.',
  },
  {
    id: 19,
    category: 'Coordination',
    prompt: 'What is "BCF" (BIM Collaboration Format) used for?',
    options: [
      'An open format for exchanging issues — viewpoints, screenshots, comments — between different BIM tools',
      'A cost-estimation standard',
      'A lightweight family file format',
      'An infrastructure-specific extension of IFC',
    ],
    correctIndex: 0,
    explanation:
      'BCF lets an issue (like a clash) found in one BIM tool be shared with, and round-tripped back from, a different tool — without exchanging the entire model.',
  },
  {
    id: 20,
    category: 'Coordination',
    prompt: 'What is the primary purpose of a Common Data Environment (CDE) on a BIM project?',
    options: [
      'A single agreed source for managing project information, organized through defined states such as Work in Progress, Shared, Published, and Archive',
      'A dedicated server used only for rendering',
      'A backup drive for the design team',
      'A clash detection engine',
    ],
    correctIndex: 0,
    explanation:
      'The CDE is the agreed information-management workflow and platform where all project information is produced, reviewed, and shared as it moves through verification and approval.',
  },
  {
    id: 21,
    category: 'Coordination',
    prompt: 'Why is a shared coordinate system across disciplines critical in BIM coordination?',
    options: [
      'It ensures all linked/federated models align correctly in the same real-world position and orientation',
      'It determines file naming conventions',
      'It only matters for rendering, not for coordination',
      'It removes the need for clash detection',
    ],
    correctIndex: 0,
    explanation:
      'Without an agreed coordinate system (survey point, project base point, true north), federated models from different disciplines can be spatially misaligned, causing false or missed clashes.',
  },
  {
    id: 22,
    category: 'Coordination',
    prompt: 'What is typically the main output of a scheduled BIM coordination meeting?',
    options: [
      'An updated clash/issue report with resolution assignments and re-check dates',
      'A finalized as-built model',
      'A new project bid',
      'A change of the CDE software vendor',
    ],
    correctIndex: 0,
    explanation:
      'Coordination meetings review current clash results, assign responsibility for fixing each issue to the right discipline, and set a timeline to re-run clash detection and confirm the fix.',
  },

  // ---------- ISO 19650 ----------
  {
    id: 23,
    category: 'ISO 19650',
    prompt: 'What does "EIR" stand for under ISO 19650, and who issues it?',
    options: [
      'Exchange Information Requirements — issued by the appointing party to state what information is needed, and when',
      'Estimated Investment Return — a financial appraisal document',
      'Engineering Inspection Report — a QA/QC document',
      'Executed Information Register — a record of completed deliverables',
    ],
    correctIndex: 0,
    explanation:
      'The EIR is issued by the appointing party (the client) before appointment, defining what information is required, in what format, and at which project stages — it forms the basis of the BEP response.',
  },
  {
    id: 24,
    category: 'ISO 19650',
    prompt: 'What is a BIM Execution Plan (BEP), and who produces the confirmed, post-appointment version?',
    options: [
      'A plan for how the EIR will be met, developed by the appointed party/lead appointed party after winning the appointment',
      'A financial budget document produced by the client before tender',
      'A software license agreement',
      'A one-time document that is never revisited after signing',
    ],
    correctIndex: 0,
    explanation:
      'The BEP sets out how the appointed team will deliver against the EIR (approach, standards, roles, technology). A pre-appointment BEP is submitted at tender; the confirmed BEP is agreed after appointment and evolves through the project.',
  },
  {
    id: 25,
    category: 'ISO 19650',
    prompt: 'Which four states typically structure a Common Data Environment\'s workflow under ISO 19650?',
    options: [
      'Work in Progress, Shared, Published, Archive',
      'Draft, Review, Approved, Rejected',
      'Concept, Design, Construction, Handover',
      'Private, Public, Restricted, Confidential',
    ],
    correctIndex: 0,
    explanation:
      'ISO 19650 describes CDE states as WIP (not yet shared), Shared (checked and available for coordination), Published (authorized for a specific use), and Archive (a record of a state at a point in time).',
  },
  {
    id: 26,
    category: 'ISO 19650',
    prompt: 'How does a Task Information Delivery Plan (TIDP) relate to the Master Information Delivery Plan (MIDP)?',
    options: [
      'A TIDP schedules deliverables from one task team; the MIDP aggregates all TIDPs into the overall project delivery schedule',
      'They are interchangeable terms for the same document',
      'TIDPs apply only during construction, MIDPs only during design',
      'The MIDP replaces the EIR entirely',
    ],
    correctIndex: 0,
    explanation:
      'Each task team (discipline) produces a TIDP listing what it will deliver and when; the lead appointed party aggregates these into a single MIDP covering the whole appointment.',
  },
  {
    id: 27,
    category: 'ISO 19650',
    prompt: 'What is the role of the "information management" function under ISO 19650?',
    options: [
      'Coordinating and enabling the information management process — e.g. CDE administration, quality checks, and facilitating collaboration',
      'Sole authorship of all discipline models',
      'Approving construction budgets',
      'Managing site health & safety only',
    ],
    correctIndex: 0,
    explanation:
      'ISO 19650 defines an information management function (often fulfilled by a BIM/information manager) that facilitates and coordinates information production, CDE workflows, and compliance with the EIR/BEP — not the authoring of design models itself.',
  },
  {
    id: 28,
    category: 'ISO 19650',
    prompt: 'What does "PIM" refer to under ISO 19650, in contrast to "AIM"?',
    options: [
      'Project Information Model — developed during design/construction, versus the Asset Information Model (AIM) used to operate the completed asset',
      'Personal Information Management — an individual\'s task tracker',
      'Preliminary Investment Model — an early cost estimate',
      'Primary Information Modeler — the lead BIM author',
    ],
    correctIndex: 0,
    explanation:
      'The PIM is developed and used during the delivery phase (design/construction). On handover, relevant information feeds into the AIM, used to operate and maintain the completed built asset.',
  },
  {
    id: 29,
    category: 'ISO 19650',
    prompt: 'ISO 19650 was developed from, and internationalizes, which earlier BIM standard?',
    options: [
      'The UK\'s BS 1192 and PAS 1192-2 series',
      'ISO 9001 quality management',
      'LEED certification standards',
      'ASHRAE 90.1',
    ],
    correctIndex: 0,
    explanation:
      'ISO 19650 (Parts 1 and 2) was built from the UK\'s BS 1192 and PAS 1192-2 frameworks, internationalizing many of the same CDE and information-management concepts.',
  },
]

export const TOTAL_QUESTIONS = questions.length
export const QUESTION_TIME_SECONDS = 25
